// Build script to generate Swift bindings using uniffi_bindgen library
// This can be run with: cargo run --manifest-path build_and_generate.toml

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    println!("🦀 Building quantified-core and generating Swift bindings...\n");

    // Step 1: Build the library
    println!("📦 Step 1: Building Rust library...");
    let status = Command::new("cargo")
        .args(&["build", "--lib", "--release"])
        .status()
        .expect("Failed to run cargo build");

    if !status.success() {
        eprintln!("❌ Failed to build library");
        std::process::exit(1);
    }
    println!("✅ Library built successfully\n");

    // Step 2: Generate Swift bindings
    println!("📝 Step 2: Generating Swift bindings...");

    let lib_path = PathBuf::from("target/release/libquantified_core.dylib");
    let out_dir = PathBuf::from("target/swift-bindings");

    std::fs::create_dir_all(&out_dir).expect("Failed to create output directory");

    // Use uniffi_bindgen library to generate bindings
    generate_swift_bindings(&lib_path, &out_dir);

    println!("\n✅ Complete!");
    println!("📁 Swift bindings generated in: target/swift-bindings/");
    println!("\nNext steps:");
    println!("1. Copy quantified_core.swift to your Xcode project");
    println!("2. Add libquantified_core.dylib to your app bundle");
    println!("3. Import and use the Swift API");
}

fn generate_swift_bindings(lib_path: &PathBuf, out_dir: &PathBuf) {
    // For now, create a placeholder
    // TODO: Use uniffi_bindgen::generate_bindings() once we figure out the API

    let swift_file = out_dir.join("quantified_core.swift");
    let placeholder = r#"// Swift bindings for quantified-core
// Generated by uniffi

// TODO: These bindings will be automatically generated
// For now, use the QuantifiedCore.swift wrapper

import Foundation

// Placeholder - actual bindings will be generated here
"#;

    std::fs::write(&swift_file, placeholder)
        .expect("Failed to write Swift bindings");

    println!("✅ Created placeholder: {:?}", swift_file);
    println!("⚠️  Full uniffi binding generation requires uniffi_bindgen::generate_bindings()");
}
